# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab401ec2e13279d175977276a54ffb3398f9c4bf72a78db182f9191ff44730687e424f256265780dbdf4fe2638ae17712abdeb9e8f74b379885ec241c85b1396

test:
  secret_key_base: 2dba73c87b44181eba83a4c742929a70535d2e9d2223d23c845a5afc077d2555e335cbb5d90c3a0860e08986e2c29c1de9ccd0b8e7fb57cc2c9c34fc809ae277

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
